


[core]
name: DEAV_RocketNoJetpack
class: CustomUnitMetadata
tags: engi
showInEditor: false

price: 1400
maxHp: 400
mass: 6000
armour: 10
techLevel: 1
buildSpeed: 0.0006

fogOfWarSightRange: 20

radius: 23
isBio: false
softCollisionOnAll: 0
# Energy system
energyMax: 10
energyRegen: 0.05
energyRegenWhenRecharging: 0.04
energyNeedsToRechargeToFull: true
maxShield: 300
shieldRegen: 0.15


[hiddenAction_buff]
autoTrigger: if self.hasUnitInTeam(withtag='thebuffer', withinRange=500)
setUnitStats: armour = 20, maxHp = 500, shootDamageMultiplier = 1.5, shield = 450, shieldRegen = 0.25
[hiddenAction_debuff]
autoTrigger: if not self.hasUnitInTeam(withtag='thebuffer',withinRange=500)
resetCustomTimer: true
[graphics]
total_frames: 1

image:        deavflyinhjetno.png
image_wreak:  NONE
image_turret: deavflyimgrpg.png

image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2

# Body follows turret rotation
lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretMultiTargeting: true

turretSize: 18
turretTurnSpeed: 3

maxAttackRange: 350
shootDelay: 15
turretRotateWithBody: true

# --- Turrets ---

# Base (dummy, invisible pivot)
[turret_1]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
recoilOffset: -5
recoilOutTime: 7
recoilReturnTime: 14
invisible: true
canShoot: false



# Heavy launcher (special)
[turret_4]
attachedTo: 1

x: 20
y: 10
idleDir: 0
turnSpeed: 3.0
turnSpeedAcceleration: 0.8
projectile: 3
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
slave: false
energyUsage: 2



[projectile_3]
directDamage: 255
areaDamage: 50
areaRadius: 50
life: 250
speed: 6
frame: 10
lightColor: #FFE92B
lightSize: 0.6
trailEffect:true
largeHitEffect:true
armourIgnoreAmount:20
# --- Movement ---

[movement]

movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 5.0
turnAcceleration: 0.5

moveSlidingMode: false
moveIgnoringBody: false
reverseSpeedPercentage: 1


