
[core]
name: mini_laser_turret
techLevel: 2
class: CustomUnitMetadata
#price: 2
mass: 1500
showInEditor: false
maxHp: 9000


buildSpeed: 0.0002
radius: 15
displayRadius:12

fogOfWarSightRange:5
transportSlotsNeeded: 1

isBio: false
softCollisionOnAll: 3

showOnMinimap: false

#canNotBeDirectlyAttacked: true
isUnrepairableUnit: true

ignoreInUnitCapCalculation: true

disableDeathOnZeroHp: true


isUnselectable: true
isUnselectableAsTarget: false



price: 18000
energyMax: 12
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.04
#maxHp: 2000

[graphics]
total_frames: 1
image: dot.png
image_turret: lasert.png
scaleImagesTo: 15
scaleTurretImagesTo: 10

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 23
turretTurnSpeed: 6

maxAttackRange: 150
shootDelay: 13


[turret_1]

x: 0
y: 0



shoot_sound:firing3
shoot_sound_vol:0.15

shoot_light:#FFEECCCC



idleSweepAngle:20
idleSweepDelay:120
idleSweepSpeed:0.3
energyUsage: 1
size:15 


[projectile_1]

#=== for the beam effect ===
life: 30

instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

beamImage:      SHARED:beam3.png
beamImageEnd:   SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
#beamImageOffsetRate: 1.5
beamImageOffsetRate: 2

explodeEffect: NONE
explodeEffectOnShield: NONE



sweepOffsetFromTargetRadius:0.4
#sweepOffset: x
sweepSpeed:10



directDamage: 15


color: #8B0000



[movement]
movementType: NONE




