
[core]
name: Roach
tags: engi
displayText: Roach 



class: CustomUnitMetadata
price: 50
maxHp: 25
mass: 1


techLevel: 1

buildSpeed: 5s
availableInDemo: true

radius: 2
displayRadius: 3

builtFrom_1_name: BS_DEAV_Factory
builtFrom_1_pos:  4










[graphics]

total_frames: 1
image:        base.png
image_wreak:  NONE
image_turret: NONE
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#imageScale:0.7
turretImageScale:0.7

lock_body_rotation_with_main_turret: true

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1



[attack]
isMelee:true
meleeEngangementDistance: 200
turretRotateWithBody: false
maxAttackRange: 4

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 9
#turretTurnSpeed: 2

#aimOffsetSpread:0.4

shootDelay: 1

isFixedFiring: true



[turret_1]
invisible: true
x: 0
y: 0
idleDir:0



canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
projectile: 1
size: 10

delay: 50

energyUsage: 0

recoilOffset: 3
recoilOutTime: 6
recoilReturnTime: 18

turnSpeed: 3.9
turnSpeedAcceleration: 0.2

[projectile_1]

directDamage: 26

life: 50
trailEffect: false
largeHitEffect: false
instant: true


frame: 4


autoTargetingOnDeadTarget: false

wobbleAmplitude: 0.4
wobbleFrequency: 0.8s





[movement]
movementType: LAND



reverseSpeedPercentage: 0.6

moveSpeed: 4
moveAccelerationSpeed: 0.2
moveDecelerationSpeed: 0.6


#body_rotation_with_main_turret means this is not used
maxTurnSpeed: 99
turnAcceleration: 99


moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181





