[core]
name: EXecutioner-2000
displayText: EXecutioner-2000
class: CustomUnitMetadata
price: 10000
maxHp: 2500
mass: 9000
tags: Airship
showInEditor: true
footprint: -1,-1,1,1
#used for placement, and placement of other buildings
constructionFootprint:-1,-1,1,1

buildingToFootprintOffsetY:5

#buildingToFootprintOffsetX:20
techLevel: 1
buildSpeed: 0.08
#availableInDemo: true

radius: 35
displayRadius: 35
buildingSelectionOffset: -8
experimental:true
isBuilding: true
isBio: false

builtFrom_1_name: combatEngineer
builtFrom_1_pos:  7

builtFrom_2_name: mechEngineer
builtFrom_2_pos:  6


numBitsOnDeath: 20

[graphics]
total_frames: 1

image:        base2.png
image_wreak:  NONE
image_turret: Executioner-2000gun.png

scaleTurretImagesTo: 32
teamColoringMode:hueShift

image_shadow: NONE
shadowOffsetX:2
shadowOffsetY:2

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:  true
canAttackUnderwaterUnits: false

turretSize: 22
turretTurnSpeed: 1


maxAttackRange:650
shootDelay: 80

#stopTargetingAfterFiring:true

[turret_1]
x: 0
y: 0
projectile:orb
barrelX:0
barrelY:14

image_drawOffsetY:10

turnSpeed:0.7
turnSpeedAcceleration: 0.1
image: Executioner-2000gun.png
image_applyTeamColors:false
shouldResetTurret: false
idleDir: 1
idleSpin: 0.3
#warmup: 2s
delay:10s
recoilOffset:-10
recoilOutTime:0.1
recoilReturnTime:8
shoot_sound: railgun.ogg
shoot_sound_vol:0.12
[projectile_orb]
life: 225
drawSize:0.1
instant:false
speed: 15
image: Executioner-2000orb.png
shieldDamageMultiplier: 150

directDamage: 1000
teamColorRatio:0

areaDamage:1500
areaRadius: 75
targetGround: true
pushForce: 2
effectOnCreate: CUSTOM:projectileLight
spawnUnit: orbc
explodeEffect: CUSTOM:projectileLight
explodeEffectOnShield: CUSTOM:projectileLight
armourIgnoreAmount:100
trailEffect:true
areaHitAirAndLandAtSameTime: true
[effect_explosion_displacement]
drawType: displacement
priority: high
image: SHARED:shockwave_normal_128.png
life: 60
fadeOut: true
fadeInTime: 2

attachedToUnit: true
color: #A5B1FF
scaleFrom: 1.0
scaleTo: 1.3
alpha: 0.3
drawUnderUnits:false

alwayStartDirAtZero: true




[effect_projectileLight]
priority:high

image: SHARED:light_50.png
life: 200
fadeOut: true
attachedToUnit: true
color: #A5B1FF
fadeInTime:8
scaleFrom: 2
scaleTo: 3
alpha: 0.8
drawUnderUnits:false
liveAfterAttachedDies: false
teamColorRatio:0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]
maxEachBase: 1
maxGlobal:3

buildPriority: 0.01
noneGlobalExtraPriority: 0.06