
[core]
name: misslerain
techLevel: 2
class: CustomUnitMetadata
#price: 2
mass: 1500
showInEditor: false
maxHp: 9000



buildSpeed: 0.0002
radius: 15
displayRadius:12

fogOfWarSightRange:5
transportSlotsNeeded: 1

isBio: false
softCollisionOnAll: 3

showOnMinimap: false

#canNotBeDirectlyAttacked: true
isUnrepairableUnit: true

ignoreInUnitCapCalculation: true

disableDeathOnZeroHp: true


isUnselectable: true
isUnselectableAsTarget: false



price: 18000
energyMax: 10
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.017
#maxHp: 2000

[graphics]
total_frames: 1
image: dot.png
scaleImagesTo: 400


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 4
turretTurnSpeed: 6
maxAttackRange: 600
shootDelay: 5
turretMultiTargeting: true

[turret_1]

x: 0
y: 0

turnSpeed: 3.0
turnSpeedAcceleration: 0.8
projectile: 1
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true

energyUsage: 1

[projectile_1]


targetGround: true
areaDamage: 300
areaRadius: 150
ballistic: true
life: 360
speed: 4
frame: 10
targetGroundSpread: 100
areaHitAirAndLandAtSameTime: true


armourIgnoreAmount: 100



[movement]
movementType: NONE




