[core]
name: V-3
class: CustomUnitMetadata
price: 4600000
maxHp: 15000
mass: 250
techLevel: 1

availableInDemo: true
radius: 11
displayRadius: 13
autoTriggerCooldownTime: 2s
fogOfWarSightRange: 45
buildSpeed: 250s
#15 = default
tags: earthmover,airship,coil
fogOfWarSightRangeWhileNotBuilt: 15
isBio: false
energyMax: 45
energyRegen: 0
energyRegenWhenRecharging: 0.1
armourMinDamageToKeep: 0
builtFrom_2_name: BS_DEAV_Factory
builtFrom_2_pos:  1.1

# for heal on kill and the weapon slot system
@memory lastHealKills: float
@memory activeSlot: float 

#enraged system
[hiddenAction_enrage]
autoTrigger: if self.hp(lessThan=6500) and not self.hasFlag(id=10)
setUnitStats: shootDamageMultiplier += 1.2, shootDelayMultiplier -= 0.6
 showMessageToAllPlayers: // +ENRAGED \\
 addResources: setFlag=10

 [hiddenAction_deenrage]
autoTrigger: if self.hasFlag(id=10) and self.hp(GreaterThan=6500)
setUnitStats: shootDamageMultiplier -= 1.2, shootDelayMultiplier += 0.6
 addResources: unsetFlag=10
# heal on kill + becoming stronger per kill
[hiddenAction_healonkill]
autoTrigger: if self.kills() > memory.lastHealKills and not self.hasFlag(id=1)
addResources: hp=550, setFlag=1
setUnitStats: shootDamageMultiplier += 0.09 , shootDelayMultiplier -= 0.005
setUnitMemory: lastHealKills = self.kills()
alsoQueueAction: healonkill_reset
allowMultipleInQueue: true
[hiddenAction_healonkill_reset]
autoTrigger: if self.hasFlag(id=1)
buildSpeed: 0.05s
addResources: unsetFlag=1

#block actions, prob could be combined with the parry actions, but if it works dont touch it

[hiddenAction_block]
autoTriggerOnEventRecursionLimit: 1
autoTriggerOnEvent: tookDamage
alsoQueueAction: block_reset
#autoTrigger: if self.hasTakenDamage(withinSeconds=1)
requireConditional: if not self.hasFlag(id=2)  and self.customTimer(laterThanSeconds=3)
setUnitStats: armour=99999
addResources: setFlag=2
allowMultipleInQueue: true

[hiddenAction_block_reset]
autoTrigger: if self.hasFlag(id=2) 
#requireConditional: if self.hasFlag(id=2) and self.hasTakenDamage(withinSeconds=5)
buildSpeed: 3s
setUnitStats: armour=0
addResources: unsetFlag=2, hp=500
allowMultipleInQueue: true
# parry actions
[hiddenAction_parry]
autoTriggerOnEvent: tookDamage
requireConditional: if  not self.hasFlag(id=6)  and self.customTimer(laterThanSeconds=15) 
addResources: setFlag=6,hp=750
fireTurretXAtGround: parry
fireTurretXAtGround_withTarget: lastDamagedBy
buildSpeed: 3s
resetCustomTimer:true
allowMultipleInQueue: true
[hiddenAction_parry_reset]

autoTrigger: if self.hasFlag(id=6) and self.customTimer(laterThanSeconds=0.1)
buildSpeed: 2s 
addResources: unsetFlag=6
allowMultipleInQueue: true
#weapon slot system, could be optimized or done in a diffent way
[hiddenAction_slotInit]
# Runs once on creation to set activeSlot to 1 (default start)
autoTriggerOnEvent: created
 setUnitMemory: activeSlot = 1
 showMessageToAllPlayers: // Blood is Fuel, this warfare is full \\
[hiddenAction_fired_slot1]
requireConditional: if memory.activeSlot == 1 and self.energy() == 0
setUnitMemory: activeSlot = 2
addResources: setFlag=4

[hiddenAction_fired_slot2]
requireConditional: if memory.activeSlot == 2 and self.energy() == 0
setUnitMemory: activeSlot = 3
addResources: setFlag=3

[hiddenAction_fired_slot3]
requireConditional: if memory.activeSlot == 3 and self.energy() == 0
setUnitMemory: activeSlot = 4
addResources: setFlag=3
[hiddenAction_fired_slot4]
requireConditional: if memory.activeSlot == 4 and self.energy() == 0
setUnitMemory: activeSlot = 5
addResources: setFlag=3

[hiddenAction_fired_slot5]
requireConditional: if memory.activeSlot == 5 and self.energy() == 0
setUnitMemory: activeSlot = 6
addResources: setFlag=3

[hiddenAction_fired_slot6]
requireConditional: if memory.activeSlot == 6 and self.energy() == 0
setUnitMemory: activeSlot = 1
addResources: setFlag=3

[hiddenAction_weaponCooldown]
autoTrigger: if self.hasFlag(id=3)  
buildSpeed: 3s  
addResources: energy=45, unsetFlag=3
allowMultipleInQueue: true
[hiddenAction_weaponCooldownslower]

autoTrigger: if self.hasFlag(id=4) 
buildSpeed: 5s
addResources: energy=45, unsetFlag=4
allowMultipleInQueue: true

# dash actions

[hiddenAction_dashOnHit]
# Triggers when damage is received AND dash is ready
autoTriggerOnEvent: tookDamage
requireConditional: if  not self.hasFlag(id=5)
allowMultipleInQueue: true
addWaypoint_type: move
addWaypoint_target_fromReference: self.getOffsetRelative(x=rnd(-150,150),y=rnd(-50,50))
# Spike speed for the burst
setUnitStats: moveSpeed=150, armour = 15
alsoQueueAction: dashOnHit_slowdown
# Start cooldown
addResources: setFlag=5
#resetCustomTimer: true

[hiddenAction_dashOnHit_slowdown]
# Cuts speed back to normal after 0.2s (the burst window)
autoTrigger: if self.hasFlag(id=5)
buildSpeed: 2s
setUnitStats: moveSpeed=2, armour = 0
alsoQueueAction: dashOnHit_reset
allowMultipleInQueue: true
[hiddenAction_dashOnHit_reset]
# Full cooldown - re-enables dash after 5s
autoTrigger: if self.hasFlag(id=5)
buildSpeed: 15s
addResources: unsetFlag=5
allowMultipleInQueue: true
[graphics]
total_frames: 1
image: dot.png
image_wreak:  NONE
image_turret:dot.png
scaleImagesTo: 5
scaleTurretImagesTo: 5
#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1
splastEffect: true
#dustEffect: true
movementEffect: CUSTOM:scoutTrail
movementEffectRate: 14
teamColorsOnTurret: true

[attack]
turretRotateWithBody:  true
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
turretSize: 7
turretTurnSpeed: 600
maxAttackRange: 700
shootDelay: 10

isFixedFiring: false
[turret_1]

x: 0
y: 0
idleDir:0

turnSpeed: 50
#59
turnSpeedAcceleration:1

canShoot: false
size: 5
image:v-3.png


invisible: false

[turret_revolver1]
attachedTo: 1

slave: true
x: 15
y: 15
idleDir:0
projectile: 1
image: rev.png
turnSpeed: 5
shoot_sound: Shoot1.ogg
shoot_sound_vol:1
shoot_flame:small
shoot_light:#FFccCCEE
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
canAttackCondition: if memory.activeSlot == 1 and not self.hasFlag(id=3)
invisible: if memory.activeSlot != 1 
energyUsage: 5
onShoot_triggerActions: fired_slot1

#can bounce up to 2 more units
[turret_revolver2]
attachedTo: 1
slave: true
x: 15
y: 15
idleDir:0
projectile: 6
image: rev2.png
turnSpeed: 5
shoot_sound: Shoot1.ogg
shoot_sound_vol:1
shoot_flame:small
shoot_light:#FFccCCEE
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
canAttackCondition: if memory.activeSlot == 5 and not self.hasFlag(id=3)
invisible: if memory.activeSlot != 5
energyUsage: 5
onShoot_triggerActions: fired_slot5

#overcharged attack if there's more than 10 untis in a 250 px area
[turret_tau]
attachedTo: 1
slave: true
x: 15
y: 15
image:minitau.png
idleDir:0   
projectile: 2

altProjectile: 3
altProjectileCondition: if self.numberOfUnitsInEnemyTeam(withinRange=250) > 10

turnSpeed: 5
canAttackCondition: if memory.activeSlot == 2 and not self.hasFlag(id=4)
invisible: if memory.activeSlot != 2     
shoot_sound: tau-cannon-firing.ogg
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFccCCEE
onShoot_triggerActions: fired_slot2
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
energyUsage: 3

#can "parry" (even less like a parry than the base parry)
[turret_shotgun]
attachedTo: 1
slave: true
x: 15
y: 15
idleDir:0
projectile: 4
size: 7
delay: 69
turnSpeed: 5
altProjectile: shotgunparry
altProjectileCondition: if self.numberOfUnitsInEnemyTeam(withinRange=100) > 1 and self.hasTakenDamage(withinSeconds=2)
shoot_sound:shotgun.ogg
shoot_sound_vol:1
shoot_flame:small
shoot_light:#FFccCCEE
onShoot_triggerActions: fired_slot3
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
image: shoting.png

canAttackCondition: if memory.activeSlot == 3 and not self.hasFlag(id=3)
invisible: if memory.activeSlot != 3
energyUsage: 9

[turret_RL]
attachedTo: 1
slave: true
x: 15
y: 15
idleDir:0
projectile: 5
shoot_sound: rpg.ogg
size: 7
turnSpeed: 5
image: rl.png
shoot_sound_vol: 1
delay: 36
shoot_flame:small
shoot_light:#FFccCCEE
onShoot_triggerActions: fired_slot4
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
canAttackCondition: if memory.activeSlot == 4 and not self.hasFlag(id=3)
invisible: if memory.activeSlot != 4
energyUsage: 9

#chains and pens though other units
[turret_Railcannon]
attachedTo: 1
slave: true
x: 15
y: 15
idleDir:0
projectile: 7
shoot_sound: rpg.ogg
size: 7
turnSpeed: 5
image: railing.png
shoot_sound_vol: 1
delay: 36

shoot_light:#FFEEEE00
warmup:5
chargeEffectImage: SHARED:lighting_charge.png
onShoot_triggerActions: fired_slot6
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
canAttackCondition: if memory.activeSlot == 6 and not self.hasFlag(id=3)
invisible: if memory.activeSlot != 6
energyUsage: 45

[turret_parry]
x: 0
y: 0
invisible: true
projectile: parryed
canAttackCondition: if self.hasFlag(id=6)
turnSpeed: 999
shoot_sound: parryer.ogg
shoot_sound_vol: 2
onShoot_triggerActions: parry_reset
[projectile_2]
directDamage: 105
life: 360
speed: 6
frame: 5
armourIgnoreAmount:2500
color: #FF5C00
lightColor: #FF5C00

[projectile_3]
directDamage: 115
areaDamage: 50
areaRadius: 35
spawnUnit: TAUP
life: 360
speed: 6
armourIgnoreAmount:2500
frame: 5
color: #FF5C00
hullDamageMultiplier:1
pushForce: 3
pushVelocity: 3
lightColor: #FF5C00
lightSize:0.7

[projectile_1]
directDamage: 100
life: 360
speed: 6
armourIgnoreAmount:2500
frame: 5

[projectile_4]
directDamage: 15
areaDamage: 15

life: 360
speed: 6
frame: 5
armourIgnoreAmount:2500
trailEffect:true
largeHitEffect:false
pushForce:1
turnSpeed:0
spawnProjectilesOnCreate:4(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),4(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),4(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),4(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),4(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),4(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1)
disableLeadTargeting:true
retargetingInFlight:true
autoTargetingOnDeadTargetRange:0
autoTargetingOnDeadTargetLead:0
retargetingInFlightSearchDelay:0
retargetingInFlightSearchRange:0
retargetingInFlightSearchLead:0

[projectile_5]
life:100
speed:25
armourIgnoreAmount:2500
frame: 10
drawSize:1
lightColor:#FFFFAA55
lightSize:0.7
trailEffect:true
largeHitEffect:false
areaDamage: 210
areaRadius: 75
targetGround: true

[projectile_6]
directDamage: 100
life: 360
speed: 6
frame: 5
armourIgnoreAmount:2500
spawnUnit:shooter

[projectile_7]
directDamage: 250
life: 25
speed: 6
armourIgnoreAmount:2500
spawnUnit:Chains1,lighting,Chains1
instant: true
lightingEffect: true
largeHitEffect: true
drawSize: 3
shieldDamageMultiplier: 1

[projectile_parryed]
armourIgnoreAmount: 3500
life: 200
speed: 50
frame: 9
drawSize: 1
areaRadius: 20
areaDamage: 500
color: #ca5e33
[projectile_shotgunparry]
armourIgnoreAmount: 3500
life: 200
speed: 50
frame: 9
drawSize: 1
areaRadius: 35
areaDamage: 600
[leg_1]
x: -15
y: 0
attach_x: -8
attach_y: 0
moveSpeed: 3

rotateSpeed: 10

heightSpeed: 0.8
resetAngle:25

image_leg:  leg.png
image_foot: foot_med.png

#draw_foot_on_top: true
#dust_effect: false

holdDisMin: 11
holdDisMax: 26



[leg_2]
x: 15
y: 0
attach_x: 8
attach_y: 0
copyFrom: 1



[effect_scoutTrail]
createWhenOverLiquid: false
createWhenZoomedOut: false
priority:low
life: 50
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime:5
scaleFrom: 0.7
scaleTo: 3.2
alpha: 0.9
drawUnderUnits:true
ySpeedRelative:-0.1
xSpeedRelativeRandom:0.2
atmospheric: true
stripIndex:dust


#couldnt get this to work how i wanted to
[attachment_whip]
x:0
y:0
canAttack:false
isVisible: false
onCreateSpawnUnitOf: whip
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[movement]
movementType: OVER_CLIFF_WATER 
moveSpeed: 2
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1

maxTurnSpeed: 7
turnAcceleration: 2.5

moveSlidingMode: false
moveIgnoringBody: false
moveSlidingDir: 0