
[core]
name: SH_MEGA_HELI
class: CustomUnitMetadata
price:2840000
maxHp: 50000
mass: 3000
armour: 69
energyMax: 2
energyRegen: 0.01
energyNeedsToRechargeToFull: true
experimental: true
transportSlotsNeeded: 500
extraBuildRangeWhenBuildingThis: 100

availableInDemo: true
generation_credits: 15
generation_resources: Byzantium=0.05
radius: 150
displayRadius: 9
nukeOnDeath: true
nukeOnDeathDamage: 5000
nukeOnDeathRange: 500
transportUnitsKillOnDeath: false
isBio: false
maxShield: 1500
shieldRegen: 0.000002
shieldRenderRadius: 200
transportUnitsHealBy: 50
maxTransportingUnits: 25
tags:Airship
buildSpeed: 160s

fogOfWarSightRange: 50


#(left, up, right, down)
footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,2
[hiddenAction_warn]
autoTriggerOnEvent:created
showMessageToAllPlayers: // Warning! The siren call of death! \\

[graphics]

total_frames: 1
image:  SHMEGA.png

image_turret:solartrurret.png
scaleImagesTo: 400
#scaleImagesTo: 20
#scaleTurretImagesTo: 9




#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1



[attack]


canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false


turretSize: 4
#turretTurnSpeed: 2

aimOffsetSpread:0.4


maxAttackRange: 1050
shootDelay: 30

turretMultiTargeting: true
[turret_solarflare]
invisible: true

x: 0
y: 150
idleDir:0
limitingAngle: 80
projectile: 1
clearTurretTargetAfterFiring: true
turnSpeed: 15
turnSpeedAcceleration: 15

shoot_flame: large
shoot_sound: large_gun_fire2
shoot_sound_vol: 1


recoilOffset:  -10
recoilOutTime: 10
recoilReturnTime: 15
energyUsage: 1




#recoilOffset: -2
#recoilOutTime: 10
#recoilReturnTime: 14




shoot_light: #00FFEEAA


[arm_1]
x:0
y: -90
image_end:heli.png

drawOverBody: true


spinRate:50



[arm_2]
x:0
y:130
image_end:heli.png

drawOverBody: true




spinRate:50



[projectile_1]






armourIgnoreAmount: 10000

life: 6000
directDamage: 900
areaDamage: 250
areaRadius: 150

frame: 10
drawSize: 1.5
speed: 50
largeHitEffect: true


[attachment_tau]
x:90
y:140
canAttack:true
idleDir: 65
isVisible: true
onCreateSpawnUnitOf: TAUCANNON
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[attachment_spawn]
x:0
y:0

canAttack:true
idleDir: 65
isVisible: true
onCreateSpawnUnitOf: spawner
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[attachment_tau2]
x:-90
y:-105
canAttack:true
idleDir: -65
isVisible: true
onCreateSpawnUnitOf: Executioner3500
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[attachment_ele]
x:70
y:-110
canAttack:true

isVisible: true
onCreateSpawnUnitOf: ele
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[attachment_laser]
x:-95
y:145
canAttack:true
isVisible: true
onCreateSpawnUnitOf: laser_turretSH
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[attachment_rocket1]
x:130
y:30
canAttack:true
isVisible: true
onCreateSpawnUnitOf: misslerain
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false
[attachment_rocket2]
x:-130
y:30
canAttack:true
isVisible: true
onCreateSpawnUnitOf: misslerain
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true
alwaysAllowedToAttackParentsMainTarget: false

[decal_solor]
image: solartrurret.png
layer: beforeBody

imageScale:1
basePositionFromTurret: solarflare




[movement]


movementType: AIR

targetHeight: 70
targetHeightDrift: 2

reverseSpeedPercentage: 0.1

moveSpeed: 0.3
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06

maxTurnSpeed: 1
turnAcceleration: 0.4
slowDeathFall: true

moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181

[ai]
maxGlobal:1

useAsAttacker: true
useAsTransport: true





