
[core]
name: TAUCANNON
techLevel: 2
class: CustomUnitMetadata
#price: 2
mass: 1500
showInEditor: false
maxHp: 9000



buildSpeed: 0.0002
radius: 15
displayRadius:12

fogOfWarSightRange:5
transportSlotsNeeded: 1

isBio: false
softCollisionOnAll: 3

showOnMinimap: false

#canNotBeDirectlyAttacked: true
isUnrepairableUnit: true

ignoreInUnitCapCalculation: true

disableDeathOnZeroHp: true


isUnselectable: true
isUnselectableAsTarget: false



price: 18000
energyMax: 30
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.04
#maxHp: 2000

[graphics]
total_frames: 1
image: dot.png
image_turret: TAUSH.png
scaleImagesTo: 400


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 4
turretTurnSpeed: 6
maxAttackRange: 500
shootDelay: 5
turretMultiTargeting: true

[turret_1]

invisible: false
x: 0
y: 0

limitingAngle: 360
projectile: 1
altProjectile: 2
altProjectileCondition: if self.numberOfUnitsInEnemyTeam(withinRange=550) > 25
#size: 7
turnSpeed: 5

shoot_sound: tau-cannon-firing.ogg
shoot_sound_vol:0.3
shoot_flame:small
shoot_light:#FFccCCEE
clearTurretTargetAfterFiring: true
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
energyUsage: 1
barrelY: 40
[projectile_1]

armourIgnoreAmount: 15
directDamage: 250
life: 360
speed: 6
frame: 5
color: #FF5C00
lightColor: #FF5C00

[projectile_2]
directDamage: 300
areaDamage: 150
areaRadius: 45
spawnUnit: TAUP2
life: 360
speed: 6
frame: 5
color: #FF5C00

armourIgnoreAmount: 50
[movement]
movementType: NONE




