
[core]
name: laser_turretSH
techLevel: 2
class: CustomUnitMetadata
#price: 2
mass: 1500
showInEditor: false
maxHp: 9000



buildSpeed: 0.0002
radius: 15
displayRadius:12

fogOfWarSightRange:5
transportSlotsNeeded: 1

isBio: false
softCollisionOnAll: 3

showOnMinimap: false

#canNotBeDirectlyAttacked: true
isUnrepairableUnit: true

ignoreInUnitCapCalculation: true

disableDeathOnZeroHp: true


isUnselectable: true
isUnselectableAsTarget: false



price: 18000
energyMax: 55
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.05
#maxHp: 2000

[graphics]
total_frames: 1
image: dot.png
image_turret: turret_top_lasert2.png
scaleImagesTo: 400


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 6
turretTurnSpeed: 6
maxAttackRange: 500
shootDelay: 1
turretMultiTargeting: true

[turret_1]

invisible: false
x: 0
y: 0
idleDir:-65
limitingAngle: 360
#size: 7
turnSpeed: 5

clearTurretTargetAfterFiring: true
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
energyUsage: 1
barrelY: 15
[projectile_1]
armourIgnoreAmount: 25

life: 30
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

beamImage: SHARED:beam3.png
beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
beamImageOffsetRate: 2

explodeEffect: NONE
explodeEffectOnShield: NONE


sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10

directDamage: 45
color: #8B0000
[movement]
movementType: NONE




