
[core]
name: spawner
techLevel: 2
class: CustomUnitMetadata
#price: 2
mass: 1500
showInEditor: false
maxHp: 9000



buildSpeed: 0.0002
radius: 15
displayRadius:12

fogOfWarSightRange:5
transportSlotsNeeded: 1

isBio: false
softCollisionOnAll: 3

showOnMinimap: false

#canNotBeDirectlyAttacked: true
isUnrepairableUnit: true

ignoreInUnitCapCalculation: true

disableDeathOnZeroHp: true


isUnselectable: true
isUnselectableAsTarget: false



price: 18000
energyMax: 1
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.0001
#maxHp: 2000

[graphics]
total_frames: 1
image: dot.png
image_turret: dot.png
scaleImagesTo: 400


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 6
turretTurnSpeed: 6
maxAttackRange: 350
shootDelay: 1
turretMultiTargeting: true

[turret_1]

invisible: false
x: 0
y: 0
idleDir:-65
limitingAngle: 360
#size: 7
turnSpeed: 5

clearTurretTargetAfterFiring: true
recoilOffset: -1
recoilOutTime: 5
recoilReturnTime: 15
energyUsage: 1
warmup: 30
[projectile_1]


life: 30
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true

spawnUnit: DCR-Cloaked*3
directDamage: 0
color: #8B0000
[movement]
movementType: NONE




