[core]
name: solarflare jr
displayText: solarflare jr
displayDescription: "a huge turret made by Shadow"


maxHp: 7500
armour: 50
mass: 150000

price: 65000

class: CustomUnitMetadata

radius: 50

tags: Airship


fogOfWarSightRange: 150

energyMax: 2
energyRegen: 0
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.005

techLevel: 2
buildSpeed: 100s




isBuilding: true


builtFrom_1_name: mechEngineer
builtFrom_1_pos:  14
builtFrom_1_forceNano: true

builtFrom_2_name: combatEngineer
builtFrom_2_pos:  14
builtFrom_2_forceNano: true

#(left, up, right, down)
footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,2

[graphics]
total_frames: 1


image: solarflare_jr.png
scaleImagesTo: 75
scaleTurretImagesTo: 30
image_turret: solartrurret.png

image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2

dustEffect: true



[attack]

canAttack: true

canAttackLandUnits: true

canAttackFlyingUnits: true

canAttackUnderwaterUnits: true

maxAttackRange: 1600

shootDelay: 15

[turret_1]
x:0
y:4
turnSpeed: 0.5
projectile:1
idleDir: 180
canOnlyAttackUnitsWithTags: earthmover, super-radar
idleSpin: 0.1
size: 20
shoot_flame: large
shoot_sound: large_gun_fire2
shoot_sound_vol: 1

shoot_light: black
recoilOffset:  -10
recoilOutTime: 10
recoilReturnTime: 15
energyUsage: 1
[projectile_1]
life: 6000
directDamage: 2500
areaDamage: 250
areaRadius: 200
armourIgnoreAmount: 1500
frame: 10
drawSize: 1.5
speed: 50
largeHitEffect: true












 

[movement]

movementType: BUILDING





 
[ai]

maxGlobal: 1

buildPriority: 0.01
noneGlobalExtraPriority: 0.06







 