
[core]


name: ATMP_beam



class: CustomUnitMetadata
price: 15000
maxHp: 1500
mass: 500
armour: 50
techLevel: 2
buildSpeed: 0.0005
#availableInDemo: true

radius: 19
displayRadius: 19

isBio: false
softCollisionOnAll: 0


fogOfWarSightRange: 35

builtFrom_1_name: BS_DEAV_Factory
builtFrom_1_pos:  6

energyMax: 25
energyRegen: 0.001
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.2



[graphics]
total_frames: 2

image:        ATMP1.png
image_wreak:  NONE
image_turret: ATMPbean.png

image_shadow: AUTO
shadowOffsetX:2
shadowOffsetY:2


animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 1


dustEffect: true



[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 32
turretTurnSpeed: 2


maxAttackRange: 500
shootDelay: 20
turretMultiTargeting: true

[turret_1]
projectile:grav
x: -7
y: 14
canShoot: true
size:1
image: gravgun.png
delay:1
limitingMinRange:150
invisible: true

[turret_3]
projectile:push
x: 0
y: 0
canShoot: true
size:1
image: gravgun.png
invisible: false
delay:50
limitingRange:80
attachedTo: 1


[turret_2]
#
x: 0
y: 0

limitingRange: 275
projectile: 1

turnSpeedAcceleration: 0.9

delay:5
canShoot: true
energyUsage: 0.5




[projectile_push]
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
#pushForce:-12000 
pushVelocity:15

beamImage:      SHARED:beam3.png
beamImageEnd:   SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
#beamImageOffsetRate: 1.5
beamImageOffsetRate: 2
directDamage: 78

explodeEffect: NONE
explodeEffectOnShield: NONE
life: 15


[projectile_grav]
instant:true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
#pushForce:-12000 
pushVelocity:-1

beamImage:      SHARED:beam3.png
beamImageEnd:   SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
#beamImageOffsetRate: 1.5
beamImageOffsetRate: 2
directDamage: 0

explodeEffect: NONE
explodeEffectOnShield: NONE
life: 15
[projectile_1]
life: 30
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true

beamImage: SHARED:beam3.png
beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
beamImageOffsetRate: 2

explodeEffect: NONE
explodeEffectOnShield: NONE
shieldDamageMultiplier: 0.85

sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10

directDamage: 15
color: #FF0000

[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03

maxTurnSpeed: 2
turnAcceleration: 0.05

moveSlidingMode :false
moveIgnoringBody:false


reverseSpeedPercentage:1



