
[core]
name: DEAV_Command
class: CustomUnitMetadata
price: 8000
maxHp: 9500
mass: 9000
copyFrom: ROOT:deav.template
#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,1,1

#used for placement, and placement of other buildings
constructionFootprint: -2,-2,2,3


techLevel: 1
buildSpeed: 0.001
#availableInDemo: true

radius: 35
#displayRadius: 25
isBio: false
isBuilding: true

explodeTypeOnDeath: building

generation_credits: 15
generation_delay: 25
exit_x:-2
exit_y:-2
exit_moveAwayAmount:120

energyMax: 40
energyNeedsToRechargeToFull: true
energyRegenWhenRecharging: 0.06
energyRegen: 0.001

canBuild_1_name: setRally
canBuild_1_pos: 0.1
\
canBuild_19_pos: 18
canRepairUnits: true
canRepairBuildings: true
nanoRange: 350
nanoRepairSpeed:1
autoRepair:true 


canReclaimResources: true


nanoBuildSpeed: 1
[graphics]
total_frames: 1

image:        DEAVt7.png
image_back:   mechFactoryBottom.png
image_turret: AT2.png



scaleTurretImagesTo: 10

#AUTO
image_shadow: NONE
shadowOffsetX:1
shadowOffsetY:1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
maxAttackRange: 370

[turret_nanoTurret]

x:-13
y:15

idleDir:50
idleDirReversing: 110


turnSpeed: 4
size: 15

image: SHARED:nano_turret.png

canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

isMainNanoTurret: true




[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1


[turret_1]
x:2
y:0
turnSpeed: 0.5
projectile:1
idleDir: 180

idleSpin: 0.1
size: 20
shoot_flame: large
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.5

shoot_light: black
recoilOffset:  -5
recoilOutTime:5
recoilReturnTime: 10


[turret_2]
x:-25
y:20
canShoot: false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
invisible:true
laserDefenceEnergyUse:1
limitingRange:255
showRangeUIGuide:true




[projectile_1]
directDamage:295
life:100
speed:25
armourIgnoreAmount:23
frame: 1
drawSize:1
lightColor:#FFFFAA55
lightSize:0.7
trailEffect:true
largeHitEffect:false
[arm_1]
x:0
y:5
image_end:mechFactoryDoor.png
#y:16

[animation_openDoor]

onActions: queuedUnits
onActionsQueuedUnitPlayAt: 0.8

blendIn: 1s
blendOut: 4s

arm1_0: {x:0, y:16}
#arm1_0ms: {x:0, y:0}
#arm1_1400ms: {x:10, y:-8}

[attachment_laser]
x:-13
y:30
canAttack:true

isVisible: true
onCreateSpawnUnitOf: mini_laser_turret_4
redirectDamageToParent:true
smoothlyBlendPositionWhenExistingUnitAdded: true

[ai]

buildPriority: 0.03

noneInBaseExtraPriority: 0.04

noneGlobalExtraPriority: 0.1


maxEachBase: 1
maxGlobal: 5





