


[core]
name: DEAV_Shotgun
class: CustomUnitMetadata

price: 3000
maxHp: 800
mass: 6000
armour: 15
techLevel: 1
buildSpeed: 0.0006

fogOfWarSightRange: 20

transportSlotsNeeded: 2

radius: 23
isBio: false
softCollisionOnAll: 0

# Energy system
energyMax: 10
energyRegen: 0.01
energyRegenWhenRecharging: 0.1
energyNeedsToRechargeToFull: true

# Factories
builtFrom_1_name: BS_DEAV_Factory
builtFrom_1_pos: 7


[graphics]
total_frames: 1

image:        DBBs.png
image_wreak:  NONE
image_turret: BGB.png

image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2

# Body follows turret rotation
lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretMultiTargeting: true

turretSize: 18
turretTurnSpeed: 3

maxAttackRange: 200
shootDelay: 90
turretRotateWithBody: true

# --- Turrets ---

# Base (dummy, invisible pivot)
[turret_1]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
recoilOffset: -5
recoilOutTime: 7
recoilReturnTime: 14
invisible: true
canShoot: false

# Right cannon
[turret_2]
x: 20
y: 10
attachedTo: 1
projectile: 1
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.3
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
limitingAngle: 140
energyUsage: 2

# Left cannon
[turret_3]
x: -20
y: 10
attachedTo: 1
projectile: 2
turnSpeed: 4.0
turnSpeedAcceleration: 1.0
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.3
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
limitingAngle: 140
energyUsage: 2




[projectile_1]
life:24
speed:12
directDamage: 50
areaDamage: 30
areaRadius:10
explodeOnEndOfLife:false
frame:11
drawSize:1.2
color:#FFBB55
deflectionPower:-1
spawnProjectilesOnCreate:1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1)
turnSpeed:0
disableLeadTargeting:true
retargetingInFlight:true
autoTargetingOnDeadTargetRange:1000
autoTargetingOnDeadTargetLead:0
retargetingInFlightSearchDelay:1
retargetingInFlightSearchRange:50
retargetingInFlightSearchLead:0
armourIgnoreAmount:15
pushForce:1
pushVelocity:1
[projectile_2]

life:24
speed:12
directDamage: 50
areaDamage: 30
areaRadius:10
explodeOnEndOfLife:true
frame:11
drawSize:1.2
color:#FFBB55
deflectionPower:-1
spawnProjectilesOnCreate:1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1),1(offsetRandomY=0,offsetRandomDir=10,recursionLimit=1)
turnSpeed:0
disableLeadTargeting:true
retargetingInFlight:true
autoTargetingOnDeadTargetRange:1000
autoTargetingOnDeadTargetLead:0
retargetingInFlightSearchDelay:1
retargetingInFlightSearchRange:50
retargetingInFlightSearchLead:0
pushForce:1
pushVelocity:1



# --- Legs ---

[leg_1]
x: -8
y: 1
attach_x: -5
attach_y: -5
moveSpeed: 1.7
rotateSpeed: 7
heightSpeed: 0.7
resetAngle: 25
image_leg: legs.png

[leg_2]
x: 8
y: 1
attach_x: 5
attach_y: -5
moveSpeed: 1.7
rotateSpeed: 7
heightSpeed: 0.7
resetAngle: -25
image_leg: legs.png

# --- Movement ---

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 5.0
turnAcceleration: 0.5

moveSlidingMode: false
moveIgnoringBody: false
reverseSpeedPercentage: 1

