


[core]
name: DEAV_Basic
class: CustomUnitMetadata

price: 1400
maxHp: 800
mass: 6000
armour: 15
techLevel: 1
buildSpeed: 0.0006

fogOfWarSightRange: 20
transportSlotsNeeded: 3
radius: 23
isBio: false
softCollisionOnAll: 0

# Energy system
energyMax: 10
energyRegen: 0.01
energyRegenWhenRecharging: 0.1
energyNeedsToRechargeToFull: true

# Factories
builtFrom_1_name: BS_DEAV_Factory
builtFrom_1_pos: 7


[graphics]
total_frames: 1

image:        DBB.png
image_wreak:  NONE
image_turret: BGB.png

image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2

# Body follows turret rotation
lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretMultiTargeting: true

turretSize: 18
turretTurnSpeed: 3

maxAttackRange: 250
shootDelay: 20
turretRotateWithBody: true

# --- Turrets ---

# Base (dummy, invisible pivot)
[turret_1]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
recoilOffset: -5
recoilOutTime: 7
recoilReturnTime: 14
invisible: true
canShoot: false

# Right cannon
[turret_2]
x: 20
y: 10
attachedTo: 1
projectile: 1
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.3
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
limitingAngle: 140
energyUsage: 0.1

# Left cannon
[turret_3]
x: -20
y: 10
attachedTo: 1
projectile: 2
turnSpeed: 4.0
turnSpeedAcceleration: 1.0
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.3
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
limitingAngle: 140
energyUsage: 0.1

# Heavy launcher (special)
[turret_4]

x: 0
y: -10
idleDir: 0
turnSpeed: 3.0
turnSpeedAcceleration: 0.8
projectile: 3
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
slave: false
limitingAngle: 160
limitingRange: 350
energyUsage: 1
delay: 60  


[projectile_1]
directDamage: 40
life: 60
speed: 6
frame: 5
lightColor: #FFE92B
lightSize: 0.6
armourIgnoreAmount:20

[projectile_2]
directDamage: 4
life: 60
speed: 6
frame: 5
lightColor: #FFE92B
lightSize: 0.6
armourIgnoreAmount:20

[projectile_3]
directDamage: 150
areaDamage: 100
areaRadius: 50
life: 60
speed: 6
frame: 10
lightColor: #FFE92B
lightSize: 0.6
armourIgnoreAmount:30

# --- Legs ---

[leg_1]
x: -8
y: 1
attach_x: -5
attach_y: -5
moveSpeed: 1.7
rotateSpeed: 7
heightSpeed: 0.7
resetAngle: 25
image_leg: legs.png

[leg_2]
x: 8
y: 1
attach_x: 5
attach_y: -5
moveSpeed: 1.7
rotateSpeed: 7
heightSpeed: 0.7
resetAngle: -25
image_leg: legs.png

# --- Movement ---

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17

maxTurnSpeed: 5.0
turnAcceleration: 0.5

moveSlidingMode: false
moveIgnoringBody: false
reverseSpeedPercentage: 1

