


[core]
name: DEAV_Rocket
class: CustomUnitMetadata


tags: airship

price: 10000
maxHp: 150
mass: 6000
armour: 15
techLevel: 1
buildSpeed: 0.006

fogOfWarSightRange: 50

radius: 23
isBio: false
softCollisionOnAll: 0
unitsSpawnedOnDeath: DEAV_RocketNoJetpack

energyMax: 10
energyRegen: 0.01
energyNeedsToRechargeToFull: true
maxShield: 300
shieldRegen: 0.15

builtFrom_1_name: BS_DEAV_Factory
builtFrom_1_pos: 7


[graphics]
total_frames: 1

image:        deavflyinhjet.png
image_wreak:  NONE
image_turret: deavflyimgrpg.png

image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2

# Body follows turret rotation
lock_body_rotation_with_main_turret: true

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretMultiTargeting: true

turretSize: 18
turretTurnSpeed: 3

maxAttackRange:500
shootDelay: 25
turretRotateWithBody: true

# --- Turrets ---

# Base (dummy, invisible pivot)
[turret_1]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
recoilOffset: -5
recoilOutTime: 7
recoilReturnTime: 14
invisible: true
canShoot: false



# Heavy launcher (special)
[turret_4]
attachedTo: 1

x: 20
y: 10
idleDir: 0
turnSpeed: 3.0
turnSpeedAcceleration: 0.8
projectile: 3
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
slave: false
energyUsage: 2



[projectile_3]
directDamage: 255
areaDamage: 50
areaRadius: 50
life: 250
speed: 6
frame: 10
lightColor: #FFE92B
lightSize: 0.6
trailEffect:true
largeHitEffect:true

armourIgnoreAmount:50
# --- Movement ---

[movement]

moveSlidingMode: false
moveIgnoringBody: false
reverseSpeedPercentage: 1
movementType:AIR
moveSpeed:1.5
moveAccelerationSpeed:0.6
moveDecelerationSpeed:0.6

maxTurnSpeed:0.5
turnAcceleration:0.5
targetHeightDrift:0.3

