
[core]
name: Electrolaser_Sergeant
class: CustomUnitMetadata
price: 6000
maxHp: 150
mass: 3000
armour: 5
energyMax: 18
energyRegen: 0.01


buildSpeed: 0.0012
availableInDemo: true

radius: 15
displayRadius: 9
softCollisionOnAll: 24

isBio: false

builtFrom_1_name: BS_DEAV_Factory
builtFrom_1_pos:  3

builtFrom_2_name: BS_DEAV_Factory_t2
builtFrom_2_pos:  3

builtFrom_2_name: BS_DEAV_Factory_t3
builtFrom_2_pos:  3

builtFrom_2_name: BS_DEAV_Factory_t4
builtFrom_2_pos:  3
builtFrom_2_name: BS_DEAV_Factory_t5
builtFrom_2_pos:  3


[graphics]

total_frames: 1
image:  base.png

image_turret: gun.png
#scaleImagesTo: 20
#scaleTurretImagesTo: 9




#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1



[attack]
turretRotateWithBody: true

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false


turretSize: 4
#turretTurnSpeed: 2

aimOffsetSpread:0.4


maxAttackRange: 250
shootDelay: 100

isFixedFiring: false

[turret_1]
invisible: true

x: 0
y: 10
idleDir:0

projectile: 1


turnSpeed: 15
turnSpeedAcceleration: 15


shoot_sound:lighting_burst
shoot_sound_vol:0.5
shoot_light:#FFEEEE00


warmup:30

chargeEffectImage: SHARED:lighting_charge.png


#recoilOffset: -2
#recoilOutTime: 10
#recoilReturnTime: 14


[turret_2]
x:0
y:0
canShoot:false
canAttackFlyingUnits:false
canAttackLandUnits:false
canAttackUnderwaterUnits:false
invisible:true
laserDefenceEnergyUse:1
limitingRange:200
showRangeUIGuide:true



shoot_light: #00FFEEAA


[arm_1]
x:3
y:1
image_end:Untitled.png

drawOverBody: true


spinRate:30



[arm_2]
x:-3
y:1
image_end:Untitled.png

drawOverBody: true




spinRate:30



[projectile_1]

speed: 10
frame: 5
drawSize: 0.7

drawUnderUnits: true 


directDamage: 150


life: 50
instant: true
lightingEffect: true
largeHitEffect: true


shieldDamageMultiplier: 1
shieldDefectionMultiplier: 0.1

buildingDamageMultiplier: 0.6
spawnUnit:Chain1(spawnChance=1,maxSpawnLimit=1,skipIfOverlapping=false)
[movement]


movementType: AIR

targetHeight: 20
targetHeightDrift: 2

reverseSpeedPercentage: 0.1

moveSpeed: 1.8
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06

maxTurnSpeed: 6
turnAcceleration: 0.4


moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  181





