
[core]
name: Byzantium_Borclasite_extractor
displayLocaleKey: Byzantium Borclasite extractor
price: 6000
maxHp: 2000
techLevel: 1
buildSpeed: 0.0010

generation_resources: Byzantium=0.2
generation_delay: 60
mass: 9000


footprint: -1,-1,1,1
#used for placement, and placement of other buildings
constructionFootprint:-1,-1,1,1



radius: 18
displayRadius:20

isBuilding: true

placeOnlyOnResPool: true

numBitsOnDeath: 16
hideScorchMark: true

builtFrom_1_name: builder
builtFrom_1_pos:  1

[action_trade1]
text: Trade 10
description: Trades 10  Byzantium Borclasite for 1500 credits
addResources: credits=1500
price: Byzantium=10




[action_trade2]
text: Trade 100
description: Trades 100  Byzantium Borclasite for 15000 credits
addResources: credits=15000
price: Byzantium=100

[action_trade3]
text: Trade 1000
description: Trades 1000  Byzantium Borclasite for 150000 credits
addResources: credits=150000
price: Byzantium=1000
[action_trade4]
text: Trade 10000
description: Trades 10000  Byzantium Borclasite for 1500000 credits
addResources: credits=1500000
price: Byzantium=10000
[graphics]
image:        bbmine.png






[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]
#ai adds extra rules for placeOnlyOnResPool type units

buildPriority: 0.3

recommendedInEachBasePriorityIfUnmet:0.55
recommendedInEachBaseNum: 1

noneInBaseExtraPriority: 0.43

#noneGlobalExtraPriority: 0.3



maxEachBase: 1







